import type { Metadata } from "next";
import { Inter, DM_Serif_Display } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/Footer";

const inter = Inter({ 
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter" 
});

const dmSerif = DM_Serif_Display({ 
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-serif" 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${dmSerif.variable} antialiased`}
      >
        <Header/>
        <main className="min-h-screen">
          {children}
          <Toaster />
        </main>
        <Footer/>
      </body>
    </html>
  );
}
